var sides = [
 'Miso Glazed Carrots',
 'Coleslaw',
 'Garden Salad',
 'Crisy Potatoes',
 'Sweet Potato Tots',
 'Coconut Rice',
 'Ceasar salad',
 'Shrimp Summer Rolls',
 'Garlic Butter Mushrooms',
 'Hush Puppies',
 'Cheesy Biscuits',
 'Mashed Potatoes',
 'Bittermellon',
 'Okra',
 'Cranberry Sauce',
 'Artichoke Dip',
 'Crispy Homemade Fries',
 'Mango Salsa',
 'Chili Cheese Dip',
 'Cheesy Potatoes',
 'Creamed Spinach',
 'Mushy Peas',
 'Green Bean Casserole',
 'Frog-Eyed Salad',
 'Gyoza',
 'Fried Spring Rolls',
 'Potatoes Au Gratin',
 'Creamed Corn',
 'Sashimi',
 'Tomato Bisque Soup',
 'Butternut Squash Soup',
 'Calamari',
 'Cream Cheese Wantons',
 'Naan'
]
var mains = [
  'Spaghetti and Meatballs',
  'Pineapple Chicken',
  'Shakshuka',
  'Thai Yellow Curry',
  'Bibimbap',
  'Chicken Parmesean',
  'Butternut Squash Soup',
  'BBQ Chicken Burgers',
  'Ramen',
  'Empanadas',
  'Chicken Fried Rice',
  'Sheet Pan Fajitas',
  'Margarita Pizza',
  'Taco Casserole',
  'Isaac\'s Special Dinner',
  'Hamburger',
  'Tacos',
  'Scrambled Eggs',
  'Lemon Rosemary Salmon',
  'Risotto',
  'Beef Wellington',
  'Green Curry',
  'Street Tacos',
  'Saag Paneer',
  'Empanadas',
  'Baked Mac \'n Cheese',
  'Fillet Minion',
  'Pho',
  'Chicken Cordon Blu',
  'Baked Lobster',
  'Acai Bowl',
  'Jambalaya',
  'Pad Thai',
  'Pad Se Ewe',
  'Pizza',
  'Spaghetti',
  'Bolognese',
  'Sushi',
  'Fajitas',
  'Falafel',
  'Eggs Benedict',
  'Chicken Coq Au Vin'
]
var desserts = [
  'Apple Pie',
  'Lemon Meringue Pie',
  'Black Forest Cake',
  'Banana Bread',
  'Peach Cobbler',
  'Cheesecake',
  'Funfetti Cake',
  'Baklava',
  'Flan',
  'Macarons',
  'Macaroons',
  'Chocolate Cupcakes',
  'Pavlova',
  'Pumpkin Pie',
  'Key Lime Pie',
  'Tart Tatin',
  'Croissants',
  'Eclairs',
  'Cookies \'n Cream Ice Cream',
  'Chocolate Brownie w/ Vanilla Ice Cream',
  'Fudgcicle',
  'Chocolate Chip Ice Cream',
  'French Silk Pie',
  'Chocolate Cream Pie',
  'Bailey\'s on Ice',
  'Gluten Free Brownie',
  'Creme Brulee',
  'Peach Cobbler',
  'Cherries Jubilee',
  'Peanut Butter Pie',
  'Cheese Cake',
  'Tiramisu',
  'Chocolate Cake',
  'Opera Cake',
  'Mochi',
  'Halohalo',
  'Gluten Free Croissant Pan Au Chocolate',
  'Divinity',
  'Tapioca',
  'Opera Creams',
  'Honeycomb Choclate',
  'Peanut Butter Cookies'
]

var userSides = [];
var userMains = [];
var userDesserts = [];
