var sides = [
 'Miso Glazed Carrots',
 'Coleslaw',
 'Garden Salad',
 'Crisy Potatoes',
 'Sweet Potato Tots',
 'Coconut Rice',
 'Ceasar salad',
 'Shrimp Summer Rolls',
 'Garlic Butter Mushrooms',
 'Hush Puppies',
 'Isaac\'s Special Side',
 'Cheesy Biscuits',
]
var mains = [
  'Spaghetti and Meatballs',
  'Pineapple Chicken',
  'Shakshuka',
  'Thai Yellow Curry',
  'Bibimbap',
  'Chicken Parmesean',
  'Butternut Squash Soup',
  'BBQ Chicken Burgers',
  'Ramen',
  'Empanadas',
  'Chicken Fried Rice',
  'Sheet Pan Fajitas',
  'Margarita Pizza',
  'Taco Casserole',
  'Isaac\'s Special Dinner',
  'Hamburger',
  'Tacos',
  'Scrambled Eggs',
  'Lemon Rosemary Salmon',
]
var desserts = [
  'Apple Pie',
  'Lemon Meringue Pie',
  'Black Forest Cake',
  'Banana Bread',
  'Peach Cobbler',
  'Cheesecake',
  'Funfetti Cake',
  'Baklava',
  'Flan',
  'Macarons',
  'Macaroons',
  'Chocolate Cupcakes',
  'Pavlova',
  'Pumpkin Pie',
  'Key Lime Pie',
  'Tart Tatin',
  'Croissants',
  'Eclairs',
  'Cookies \'n Cream Ice Cream',
  'Isaac\'s Choice ;)',
  'Chocolate Brownie w/ Vanilla Ice Cream',
  'Fudgcicle',
  'Chocolate Chip Ice Cream'
]

var userSides = [];
var userMains = [];
var userDesserts = [];
